### ISSUE TITLE
Eclipse issue with sdk jar

### ISSUE THREAD

**Issue by oakstair** [GoogleCloudPlatform/gradle-appengine-plugin#184]
My eclipse does not like the classpath that this plugin generates.

I get this error within eclipse

    The App Engine SDK '/Users/gunnar/.gradle/caches/modules-2/files-2.1/com.google.appengine/appengine-api-1.0-sdk/1.9.19/188d623cac7193f2f46f44dc7b76f3ba2342a09f/appengine-api-1.0-sdk-1.9.19.jar' on the project's build path is not valid (SDK location '/Users/gunnar/.gradle/caches/modules-2/files-2.1/com.google.appengine/appengine-api-1.0-sdk/1.9.19/188d623cac7193f2f46f44dc7b76f3ba2342a09f/appengine-api-1.0-sdk-1.9.19.jar' is not a directory)	davinci		Unknown	Google App Engine Problem

A cure anyone?

**Comment by loosebazooka** [comment]
Are you using gradle with the appengine tooling in eclipse?  I'm not completely sure what the interactions there are.  It appears it's trying to find your sdk directory and it's configured to that sdk-api jar.

**Comment by oakstair** [comment]
Yes we are using "Google Plugin for Eclipse" in eclipse. We are also using the eclipse gradle plugin.

We want to use gradle as build system but still be able to work in eclipse. Is this a problem?

![Eclipse Configuration](https://cloud.githubusercontent.com/assets/285490/7278286/bb3dc1ca-e914-11e4-9bae-529dad128c97.png)

**Comment by loosebazooka** [comment]
It's not clear to me the implications of using both together. The Google Plugin for Eclipse (GPE) expects to use the Eclipse builder for everything.  What parts of GPE do you need that cannot be replicated by gradle?

**Comment by oakstair** [comment]
None I guess except that we have some people here that are used to do it that way. Perhaps they will have to do it the gradle way.

**Comment by jamesmortensen** [comment]
The biggest thing GPE and Cloud Tools for Eclipse have is hot swap, not just for Java files, but also for JSP files.  This is key to having a very fast, iterative, development cycle and is really helpful when making small, iterative changes and reloading the web page to see the change.  

The hot swap in Gradle doesn't appear to be able to deal with JSP files (which is where a majority of front-end, visual code will go where a developer may be more likely to want to do a "change -> Save -> Refresh the page" cycle...  hope this helps clarify why this would be helpful to have these tools work together.

I think with Cloud Tools for Eclipse, it may be easier than with the deprecated Google Plugin for Eclipse, because the CT4E file structure now matches the Maven/Gradle default structure...
